volumes:
  redis_data:	
  postgres_data:   
  
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tarefa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"  

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
    command: ["redis-server", "--requirepass", "redis"]
    volumes:
      - redis_data:/data
